modLoader = "javafml"
loaderVersion = "[4,)"
license = "MIT"
mixins = ["samisaeinfinity.mixins.json"]

[[mods]]
modId = "samisaeinfinity"
version = "1.0.0"
displayName = "Sami's AE Infinity"
description = "Infinity bulk cells - exact copy of MEGACells structure"
authors = "Samiyuru"

[[dependencies.samisaeinfinity]]
modId = "neoforge"
type = "required"
versionRange = "[21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.samisaeinfinity]]
modId = "ae2"
type = "required"
versionRange = "[19.2,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.samisaeinfinity]]
modId = "megacells"
type = "required"
versionRange = "[4.10,)"
ordering = "AFTER"
side = "BOTH"